# Google Vertex Anthropic Provider Definition
id = "google_vertex_anthropic"
name = "Google Vertex Anthropic"
base_url = "https://us-central1-aiplatform.googleapis.com/v1"
doc = "https://cloud.google.com/vertex-ai/docs"

env = ["GOOGLE_VERTEX_API_KEY"]

exclude_models = [
  "claude-3-5-haiku@20241022",
  "claude-3-5-sonnet@20241022",
  "claude-3-7-sonnet@20250219",
  "claude-sonnet-4@20250514",
  "claude-opus-4@20250514"
]
