# Anthropic Provider Definition
id = "anthropic"
name = "Anthropic"
base_url = "https://api.anthropic.com/v1"
doc = "https://docs.anthropic.com"

env = ["ANTHROPIC_API_KEY"]

exclude_models = [
  "claude-1.0",
  "claude-1.1",
  "claude-1.2",
  "claude-1.3",
  "claude-2.0",
  "claude-2.1",
  "claude-3-sonnet-20240229",
  "claude-3-opus-20240229",
  "claude-3-5-sonnet-20240620",
  "claude-3-5-sonnet-20241022",
  "claude-3-7-sonnet-20250219",
  "claude-instant-1.0",
  "claude-instant-1.1",
  "claude-instant-1.2"
]
